package mcce.sapp.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import java.util.Date;
import org.hibernate.annotations.*;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "user")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's username
  @NotNull
  private String username;

  // The user's password
  @NotNull
  private String password;

  @CreationTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdAt")
  private Date createdAt;

  @UpdateTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updatedAt")
  private Date udpatedAt;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String username, String password) {
    this.username = username;
    this.password = password;
  }


  public long getId() {
      return this.id;
  }

  public String getUsername() {
      return this.username;
  }

  public String getPassword() {
      return this.password;
  }

  
  public Date getCreatedAt() {
      return this.createdAt;
  }

  public Date getUdpatedAt() {
      return this.udpatedAt;
  }

  public void setId(long id) {
      this.id = id;
  }

  public void setUsername(String username) {
      this.username = username;
  }

  public void setPassword(String password) {
      this.password = password;
  }

  public void setCreatedAt(Date createdAt) {
      this.createdAt = createdAt;
  }

  public void setUdpatedAt(Date udpatedAt) {
      this.udpatedAt = udpatedAt;
  }

  public void clean(){
    this.password = null;
  }

  
} // class User