package mcce.sapp.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Lob;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany  ;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.*;
import java.util.Date;
import java.util.Set;
import org.hibernate.annotations.*;

import mcce.sapp.models.*;

/**
 * An entity {{capitalizedId}} composed by {{#fields}}{{id}} {{#unless @last}}, {{/unless}} {{/fields}}.
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "{{id}}")
public class {{capitalizedId}} {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each {{id}} in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
{{#fields}}
  @NotNull
  private {{capitalizedType}} {{name}};
{{/fields}}

{{#parents}}
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name="{{lowerId}}Id")
  @JsonIgnore
  private {{capitalizedId}} {{lowerId}};
{{/parents}}

{{#children}}
  @OneToMany(mappedBy="{{../lowerId}}")
  private Set<{{capitalizedId}}> {{pluralId}};
{{/children}}


  @CreationTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdAt")
  private Date createdAt;

  @UpdateTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updatedAt")
  private Date udpatedAt;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public {{capitalizedId}}() { }

  public {{capitalizedId}}(long id) { 
    this.id = id;
  }
  
  public {{capitalizedId}}({{#fields}} {{capitalizedType}} {{name}} {{#unless @last}},{{/unless}} {{/fields}}) {
    {{#fields}}
      this.{{name}} = {{name}};
    {{/fields}}
  }

  

  public long getId() {
      return this.id;
  }


  {{#fields}}
  public {{capitalizedType}} get{{capitalizedName}}() {
      return this.{{name}};
  }
  {{/fields}}

  {{#parents}}
    public {{capitalizedId}} get{{capitalizedId}}() {
      return this.{{lowerId}};
    } 
  {{/parents}}

  {{#children}}
    public Set<{{capitalizedId}}> get{{capitalizedPluralId}}() {
      return this.{{pluralId}};
    } 
  {{/children}}


  public Date getCreatedAt() {
      return this.createdAt;
  }

  public Date getUdpatedAt() {
      return this.udpatedAt;
  }

  public void setId(long id) {
      this.id = id;
  }


  {{#fields}}
  public void set{{capitalizedName}}({{capitalizedType}} {{lowerName}}) {
      this.{{lowerName}} = {{lowerName}};
  }
  {{/fields}}

  {{#parents}}
  public void set{{capitalizedName}}({{capitalizedId}} {{lowerId}}) {
      this.{{lowerId}} = {{lowerId}};
  }
  {{/parents}}


  public void setCreatedAt(Date createdAt) {
      this.createdAt = createdAt;
  }

  public void setUdpatedAt(Date udpatedAt) {
      this.udpatedAt = udpatedAt;
  }

  
} // class