package mcce.sapp.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Lob;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany  ;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.Set;
import org.hibernate.annotations.*;

import mcce.sapp.models.*;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "comp")
public class Comp {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each article in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  private String name;
  @NotNull
  private String description;

  @ManyToOne
  @JoinColumn(name="stageId")
  private Stage stage;
  @ManyToOne
  @JoinColumn(name="teamId")
  private Team team;

  @OneToMany(mappedBy="comp")
  private Set<Hero> heroes;


  @CreationTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdAt")
  private Date createdAt;

  @UpdateTimestamp
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updatedAt")
  private Date udpatedAt;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Comp() { }

  public Comp(long id) { 
    this.id = id;
  }
  
  public Comp( String name ,  String description  ) {
      this.name = name;
      this.description = description;
  }

  

  public long getId() {
      return this.id;
  }


  public String getName() {
      return this.name;
  }
  public String getDescription() {
      return this.description;
  }

    public Stage getStage() {
      return this.stage;
    } 
    public Team getTeam() {
      return this.team;
    } 

    public Set<Hero> getHeroes() {
      return this.heroes;
    } 


  public Date getCreatedAt() {
      return this.createdAt;
  }

  public Date getUdpatedAt() {
      return this.udpatedAt;
  }

  public void setId(long id) {
      this.id = id;
  }


  public void setName(String name) {
      this.name = name;
  }
  public void setDescription(String description) {
      this.description = description;
  }

  public void setStage(Stage stage) {
      this.stage = stage;
  }
  public void setTeam(Team team) {
      this.team = team;
  }


  public void setCreatedAt(Date createdAt) {
      this.createdAt = createdAt;
  }

  public void setUdpatedAt(Date udpatedAt) {
      this.udpatedAt = udpatedAt;
  }

  
} // class